### ISSUE TITLE
请教如何令 Org-mode 的 dynamic block 展示表格

### ISSUE THREAD

**Issue by yibie** [lujun9972/lujun9972.github.com#213]
之前因为学习 org-ql 的关系，开始对 org-mode 的 dynamic block 进行了一定的了解和上手。

我现在已经清楚如何定义 columnview 里展示的类目，但比较奇怪的是，我每一次启动 dynamic block 我只能启动 columnview，而不能像其它介绍 dynamic block 的文章里写的一样，可以直接把相关的值取出来，直接填入一个 table 里进行展示。

比如暗无天日写的 《[org-mode columnview 生成任务列表](http://blog.lujun9972.win/blog/2020/05/08/%E4%BD%BF%E7%94%A8-org-mode-columnview-%E7%94%9F%E6%88%90%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8/index.html)》：
![image](https://user-images.githubusercontent.com/365484/177305950-f8f7a58d-5b6d-46cd-bb9a-feb33456d314.png)

我的只能是这样：
![image](https://user-images.githubusercontent.com/365484/177305886-c7ffda2a-29a4-49e9-b955-0e6d42998fb2.png)

**Comment by lujun9972** [comment]
什么叫“只能启动 columnview”?
从图片里看， 你填的是 :ID "XXX=XXX-XXX" 表示只从这个 ID 所指定的 heading 中读取数据，
而这个 ID entry 中没有任何内容

如果你想要从指定文件中读取展示数据，需要改成 file:/path/to/org/file

**Comment by yibie** [comment]
> 什么叫“只能启动 columnview”? 从图片里看， 你填的是 :ID "XXX=XXX-XXX" 表示只从这个 ID 所指定的 heading 中读取数据， 而这个 ID entry 中没有任何内容
> 
> 如果你想要从指定文件中读取展示数据，需要改成 file:/path/to/org/file

原来如此，感谢，已经完美解决
