### ISSUE TITLE
Discord不能用？

### ISSUE THREAD

**Issue by jingjinghack** [lujun9972/lujun9972.github.com#31]
已挂梯子...

**Comment by lujun9972** [comment]
Discord？还是Disqus？

**Comment by jingjinghack** [comment]
sry，拼错了，是disqus

**Comment by lujun9972** [comment]
我在手机上看是没问题的呀，是哪篇出了问题还是所有的都出问题了？

**Comment by jingjinghack** [comment]
![image](https://user-images.githubusercontent.com/16219523/35317154-59059750-0110-11e8-87ce-a070c673de1f.png)

**Comment by lujun9972** [comment]
我回去升级一下ego，然后重新发布试试吧

**Comment by jingjinghack** [comment]
根据console的信息，是因为里面有个js脚本没有http所以chrome没让它加载，disqus的那个脚本改成https应该就可以了。

**Comment by lujun9972** [comment]
我很好奇，为啥在手机上能行呢…

**Comment by lujun9972** [comment]
现在应该可以了吧 @jingjinghack

**Comment by jingjinghack** [comment]
可以了
